"""add_deploy_time

Revision ID: 6af40bd609f4
Revises: 3e1d2131616e
Create Date: 2022-09-22 12:50:50.699910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af40bd609f4'
down_revision = '3e1d2131616e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('last_trig', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'last_trig')
    # ### end Alembic commands ###
