"""add uid

Revision ID: 8a2272ccd952
Revises: 6af40bd609f4
Create Date: 2022-09-28 15:31:26.068659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2272ccd952'
down_revision = '6af40bd609f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_id', 'sys_users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('uid')

    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.drop_column('last_trig')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_trig', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
