"""add trigger time

Revision ID: ecae5d4cb259
Revises: 9f4ebecb2163
Create Date: 2023-09-19 14:52:11.391865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecae5d4cb259'
down_revision = '9f4ebecb2163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deploy_vms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deploy_vms', schema=None) as batch_op:
        batch_op.drop_column('trigger_at')

    # ### end Alembic commands ###
